FROM node

COPY ./frontend /code
WORKDIR /code

RUN groupadd frontend \
    && useradd -g frontend frontend \
    && mkdir /home/frontend \
    && chown frontend:frontend -R /home/frontend \
    && chown frontend:frontend -R /code

RUN chown -R frontend /usr/local

#### - - - WORKAROUND FOR BUG IN AUFS - - -
## For more details see:
#   * https://github.com/docker/docker/issues/783
#   * https://github.com/docker-library/tomcat/issues/35

RUN mv /code /code-tmp && mv /code-tmp /code && chmod -R 775 /code

#### - - - END OF WORKAROUND - -

USER frontend
RUN chown frontend:frontend -R /code
RUN cd /code && npm config set prefix /usr/local && npm -g install grunt-cli karma bower

RUN npm install && bower install

CMD ["grunt", "watch", "--force"]

