"""Added SubjectSignup

Revision ID: aa990e015f3b
Revises: 4422a35363ce
Create Date: 2016-08-26 13:30:30.824714

"""

# revision identifiers, used by Alembic.
revision = 'aa990e015f3b'
down_revision = '4422a35363ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects_signup',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects_signup')
    ### end Alembic commands ###
