"""Added Term* models

Revision ID: c12c329a63b6
Revises: 3da45596c5c1
Create Date: 2016-08-27 14:56:52.122937

"""

# revision identifiers, used by Alembic.
revision = 'c12c329a63b6'
down_revision = '3da45596c5c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('lab', 'project', 'seminary', name='termtype'), nullable=False),
    sa.Column('day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'saturday', 'sunday', name='day'), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_groups',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('term_id', 'group_id')
    )
    op.create_table('terms_signup',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reason_accepted', sa.Boolean(), nullable=False),
    sa.Column('reason_accepted_by', sa.Integer(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reason_accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('term_id', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms_signup')
    op.drop_table('terms_groups')
    op.drop_table('terms')
    ### end Alembic commands ###
